module.exports = {
  PORT: process.env.PORT || 8080,
  NODE_ENV: process.env.NODE_ENV || 'local',
  MONGODB_URI: process.env.MONGODB_URI,
  DB_NAME: process.env.DATABASE_NAME,
  JWT_TOKEN_SECRET: process.env.JWT_TOKEN_SECRET,
  userRoles: Object.freeze({
    superadmin: 'superadmin',
    executive: 'executive',
    admin: 'admin',
    fad: 'fad',
    normal: 'normal',
  }),
  paymentType: Object.freeze({
    normal: 'normal',
    advanced: 'advanced',
  }),
  documentActions: Object.freeze({
    verify: 'verify',
    approve: 'approve',
    reject: 'reject',
    acknowledge: 'acknowledge',
  }),
  documentStatus: Object.freeze({
    drafted: 'drafted',
    pending: 'pending',
    approved: 'approved',
    rejected: 'rejected',
    verified: 'verified',
    acknowledged: 'acknowledged',
  }),
  documentRemarkActions: Object.freeze({
    approved: 'approved',
    verified: 'verified',
    rejected: 'rejected',
    acknowledged: 'acknowledged',
  }),
  documentSections: {
    admin: 'admin',
    fad: 'fad',
  },
  permissions: Object.freeze({
    adminSection: ['approve', 'verify', 'reject'],
    fadSection: ['approve', 'reject', 'verify', 'acknowledge'],
  }),
  RESERVED_QUERY_WORDS: Object.freeze(['page', 'sort']),
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  AWS_REGION: process.env.AWS_REGION,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
};
